### ISSUE TITLE
Add underline to Fallback Featured Image text link.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#50]
I am going through the sidebar settings.
One thing I am seeing is this. 

---

<img width="315" alt="Screen Shot 2020-05-02 at 12 22 59" src="https://user-images.githubusercontent.com/5323259/80861571-ae321e00-8c6f-11ea-8cdc-bea14b5f42ca.png">

--

<img width="264" alt="Screen Shot 2020-05-02 at 11 52 21" src="https://user-images.githubusercontent.com/5323259/80860953-9fe20300-8c6b-11ea-9da4-cdb814c0acfa.png">

--

Notice the difference as I added underlines to the Fallback Feature Image and Reset Image text links.
![Featured-Image-underline](https://user-images.githubusercontent.com/5323259/80861644-213b9480-8c70-11ea-935c-c5bc56170fff.jpg)

Fallback Featured Image and Reset image text links are not obvious links. This could use an underline giving it a signal that it is a link and something happens. 

---------

The 0 showed up as I got a featured image and then removed the featured image again.

<img width="817" alt="Screen Shot 2020-05-02 at 11 55 45" src="https://user-images.githubusercontent.com/5323259/80860987-e0418100-8c6b-11ea-883c-f97450e8939a.png">

**Comment by paaljoachim** [comment]
NB!  The above was focused on the Custom Post Block, but the same would also be for Featured Post Term. Just remember to underline text that is a link.

**Comment by ronalfy** [comment]
We made them buttons to be clearer. Closing out.
