### ISSUE TITLE
Featured posts: Error

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#54]
Hey Ron

I am testing out the Featured Posts by Term here:
https://designkurs.com/

This error is seen:
Notice: Trying to get property ‘name’ of non-object in /home/easywebd/public_html/dev/designkurs.com/wp-content/plugins/post-type-archive-mapping/includes/blocks/featured-posts/class-posts.php on line 210

AND

The first and a few more articles further down are showing a lot more than just the excerpt.

AND

All post titles are missing.

I am using the Gridd theme from Ari https://github.com/wplemon/gridd
WordPress 5.4
Gutenberg plugin 8.0.0
Chrome
Testing is happening with a dev site of an online client site.

**Comment by paaljoachim** [comment]
Btw I am wondering if the bug is also affecting the two icons in the toolbar:
Show Excerpt and Full Content View. As either I do not really understand what they do or they are just not working correctly.

**Comment by ronalfy** [comment]
This should be fixed now. Added the excerpt and an excerpt option for length.
