### ISSUE TITLE
Featured posts: Duplicate the Display Post Excerpt setting from Custom Block and over to Featured Posts Block.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#55]
In the custom block we have this:

<img width="262" alt="Screen Shot 2020-05-02 at 14 34 06" src="https://user-images.githubusercontent.com/5323259/80864291-05d98500-8c82-11ea-8cca-462e015a0f0d.png">

In the featured posts we have this:

<img width="207" alt="Screen Shot 2020-05-02 at 14 35 08" src="https://user-images.githubusercontent.com/5323259/80864312-23a6ea00-8c82-11ea-99b1-a65ed666c5d9.png">

Please add the custom block excerpt options + text to the featured posts options.
Keeping it consistent, and identical as possible when the same option is used. We also need to control the excerpt length in the featured posts block.

**Comment by ronalfy** [comment]
This has been added to dev.
