### ISSUE TITLE
Featured Posts: Alignment toolbar bug.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#57]
https://designkurs.com/
Chrome
WP 5.4
Gutenberg plugin 8.0.0

Choosing the first option Bred Bredde

<img width="850" alt="Screen Shot 2020-05-02 at 15 06 34" src="https://user-images.githubusercontent.com/5323259/80864994-a467e500-8c86-11ea-923b-1669fcf59519.png">

Then I see this. Here I am not able to select the toolbar.
<img width="785" alt="Screen Shot 2020-05-02 at 15 06 52" src="https://user-images.githubusercontent.com/5323259/80864996-a762d580-8c86-11ea-9331-ecce09358dd8.png">

I have to save and refresh the browser. Then I get the toolbar back again.
<img width="769" alt="Screen Shot 2020-05-02 at 15 08 58" src="https://user-images.githubusercontent.com/5323259/80865034-e7c25380-8c86-11ea-803c-a36a20d552d5.png">

I switched over to Twenty Twenty theme and clicked the same Bred Bredde option and once again the toolbar went away.

There should be a toolbar showing when block is selected.
<img width="1529" alt="Screen Shot 2020-05-02 at 15 11 25" src="https://user-images.githubusercontent.com/5323259/80865080-366fed80-8c87-11ea-8591-16ce881847fb.png">

**Comment by ronalfy** [comment]
I have removed the duplicate toolbars and this seems to have fixed the issue.
