### ISSUE TITLE
Rename Custom Post Settings to Query.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#59]
<img width="328" alt="Custom Posts Settings" src="https://user-images.githubusercontent.com/5323259/80911599-9920c200-8d37-11ea-9d12-c8d2a7766f85.png">

<img width="263" alt="Query" src="https://user-images.githubusercontent.com/5323259/80911609-9e7e0c80-8d37-11ea-8323-2a8e7f32c0e1.png">

Featured Posts settings use the name Query. Custom Post Block use the name Custom Post Settings. Rename Custom Post Settings to Query.

I am working on comparing Custom Posts Block and Featured Posts By Term Block and evening out the differences.

**Comment by ronalfy** [comment]
Changed.
