### ISSUE TITLE
Term Grid: Selecting terms take too much space.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#65]
Here is an example from this dev site. 
Which I am using for the religion client site to test out things with.

https://designkurs.com/forside-test/

<img width="312" alt="Screen Shot 2020-05-03 at 14 33 17" src="https://user-images.githubusercontent.com/5323259/80914320-2ae5fa80-8d4b-11ea-8956-a6fa35873a8b.png">

Notice how much space each term (category) uses. 
Then below they should up like categories. 

I went to the frontend and back again to the backend. 
The wrong Terms are showing there though because of the bug I mentioned in another issue.

<img width="666" alt="Screen Shot 2020-05-03 at 14 38 44" src="https://user-images.githubusercontent.com/5323259/80914441-d000d300-8d4b-11ea-962d-ad9a1a7d7281.png">

I did an Inspect to see if there were any notices.
<img width="1577" alt="Screen Shot 2020-05-03 at 14 41 58" src="https://user-images.githubusercontent.com/5323259/80914498-430a4980-8d4c-11ea-8366-bf7723d66fcc.png">

**Comment by ronalfy** [comment]
@paaljoachim would it be better just to hide the terms shown above since it's a duplicate?

**Comment by paaljoachim** [comment]
Yes.

**Comment by paaljoachim** [comment]
Just a thought...
Actually another option could be to have the above bigger options show up with a drop down beside them to select a background image from the Media Library. That is if the user decides to use a background image for each category selected.

**Comment by ronalfy** [comment]
I've decided to just hide them for now.
