### ISSUE TITLE
Term Grid: Add background image from Media Library

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#66]
I selected Background image.

<img width="290" alt="Screen Shot 2020-05-03 at 14 43 45" src="https://user-images.githubusercontent.com/5323259/80914554-82389a80-8d4c-11ea-93d2-6befd28956cc.png">

As I am not using Advanced Custom Fields or Pods and I do not know what Term Meta does.
I selected Term Meta. 
Selected Image Size Large.
Field Name (Do not know what this does)
Noticed the Fallback Background Image (this needs an underline)

Found an image in the Media Library.
<img width="273" alt="Screen Shot 2020-05-03 at 14 48 56" src="https://user-images.githubusercontent.com/5323259/80914659-3df9ca00-8d4d-11ea-9dfa-9f0b70510361.png">

Noticed the tiny Apply at the very bottom of the Background Image section.
The Apply text link need to be given more space. I will create an issue for it.
Clicked it and the image is now seen in the layout.

<img width="1456" alt="Screen Shot 2020-05-03 at 14 50 20" src="https://user-images.githubusercontent.com/5323259/80914683-700b2c00-8d4d-11ea-9e46-6b852a89ccbb.png">

Updated. Then went to the frontend.
https://designkurs.com/forside-test/

Noticed this:
<img width="1552" alt="Screen Shot 2020-05-03 at 14 51 36" src="https://user-images.githubusercontent.com/5323259/80914699-9c26ad00-8d4d-11ea-968c-7c620d659f26.png">

Went back to the backend.
Switched Taxonomy from CPT to a regular category to see if that made any difference. 
It made no difference. As it gave the same error as earlier.

**Comment by ronalfy** [comment]
Fixed for all field types, ACF, Pods, and Custom Meta.
