### ISSUE TITLE
Featured Posts: Selecting category but not filling out term title

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#69]
Selecting a category it will be listed so:

![Screen Shot 2020-05-07 at 15 13 03](https://user-images.githubusercontent.com/5323259/81298608-46b40e00-9075-11ea-8c14-af86c5f2d8b4.png)

Notice it says All in the layout but I have not filled out anything in the Term title. Seen in the sidebar.

Going to the frontend. It looks like this:
![Screen Shot 2020-05-07 at 15 14 10](https://user-images.githubusercontent.com/5323259/81298700-6d724480-9075-11ea-9cd1-15f8d476dd0e.png)

Selecting a category have the category name autofill into the Term title field box.

**Comment by ronalfy** [comment]
Thanks @paaljoachim

**Comment by ronalfy** [comment]
Fixed with https://github.com/MediaRon/post-type-archive-mapping/commit/a7f0a48ac86951f1a36a713d747fe10ca341916b
