### ISSUE TITLE
Custom Post: Make button.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#75]
Hey Ron

Custom Post.
Featured image section.
![Screen Shot 2020-05-25 at 15 11 06](https://user-images.githubusercontent.com/5323259/82815714-ff61b600-9e99-11ea-9a4b-19e948e390ef.png)

Fallback Featured Image could use a button.

---

I there are also a few other places. Taking a look right now.

**Comment by paaljoachim** [comment]
Featured posts.
Same area.
![Screen Shot 2020-05-25 at 15 12 57](https://user-images.githubusercontent.com/5323259/82815841-46e84200-9e9a-11ea-9abf-2b01985f8562.png)

**Comment by paaljoachim** [comment]
Term Grid now have these buttons. From this issue:
https://github.com/MediaRon/post-type-archive-mapping/issues/67

![Screen Shot 2020-05-25 at 15 14 15](https://user-images.githubusercontent.com/5323259/82815911-739c5980-9e9a-11ea-86a1-030e08e78aaf.png)

**Comment by ronalfy** [comment]
@paaljoachim this should be fixed now.
