### ISSUE TITLE
Term Grid: Selecting Term Meta and fallback image and creates error on the frontned.

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#76]
![Screen Shot 2020-05-25 at 15 36 36](https://user-images.githubusercontent.com/5323259/82817617-95e3a680-9e9d-11ea-9fab-1fffcda43888.png)

Frontend:
![Screen Shot 2020-05-25 at 15 36 48](https://user-images.githubusercontent.com/5323259/82817622-9a0fc400-9e9d-11ea-892a-2a3373856387.png)

![Screen Shot 2020-05-25 at 15 37 45](https://user-images.githubusercontent.com/5323259/82817740-d04d4380-9e9d-11ea-8c9d-da84b65eb042.png)

![Screen Shot 2020-05-25 at 15 38 01](https://user-images.githubusercontent.com/5323259/82817743-d3483400-9e9d-11ea-9e43-33a0aaa1a919.png)

![Screen Shot 2020-05-25 at 15 38 13](https://user-images.githubusercontent.com/5323259/82817746-d511f780-9e9d-11ea-83b0-ce84ac9dc93b.png)

![Screen Shot 2020-05-25 at 15 38 35](https://user-images.githubusercontent.com/5323259/82817757-d6dbbb00-9e9d-11ea-82ad-02bb515188d6.png)

**Comment by paaljoachim** [comment]
Here is the same error. Might be a little different error message:
https://github.com/MediaRon/post-type-archive-mapping/issues/66

**Comment by ronalfy** [comment]
Fixed for all field types, ACF, Pods, and Custom Meta.
