### ISSUE TITLE
Term Grid: Add Media Library to Background Image Source

### ISSUE THREAD

**Issue by paaljoachim** [MediaRon/post-type-archive-mapping#77]
Under Display
We have the Background Type drop down option to choose 
Background Color, Gradient or image.
Selecting Background Image opens up the Background Image section below.
We have the option to use: None (can be removed), Advanced Custom Fields, Pods or Term Meta. We are missing the Media Library option here.

<img width="436" alt="Screen Shot 2020-05-25 at 17 39 15" src="https://user-images.githubusercontent.com/5323259/82827400-4017fa00-9eaf-11ea-9580-acf98c213196.png">

Two things:
1. As the user has selected to use a Background image there is not point in having None in the Background Image section drop down. As they have in the section above it selected to use an image.
2. It would be helpful to have an option to use Media Library and then set the Fallback Background Image.

**Comment by ronalfy** [comment]
I removed none and default to term meta. Using the media library as a source isn't a feasible possibility as there are different types and sizes of media. I'd rather have tutorials for each source and explain how to achieve the background images for each category. I'll add a separate issue for that.
