### ISSUE TITLE
Custom Query Blocks 5.1.0 Testing

### ISSUE THREAD

**Issue by ronalfy** [MediaRon/post-type-archive-mapping#94]
@paaljoachim et al, if you have time, I could use some help testing the new 5.1.0 features.

The release and details are here: https://github.com/MediaRon/post-type-archive-mapping/releases/tag/5.1.0-beta-1

For brevity, here's what's in the 5.1.0 release.

* Added plugin settings links.
* Added admin settings with settings and support tabs.
* Can disable blocks, page columns, archive mapping, and image sizes via options.

Some code cleanup.

<img width="672" alt="Screen Shot 2021-03-21 at 12 21 59 AM" src="https://user-images.githubusercontent.com/636521/111894835-2dd9f000-89dc-11eb-86b3-61fc7e6a0cea.png">

<img width="1269" alt="Screen Shot 2021-03-21 at 12 25 58 AM" src="https://user-images.githubusercontent.com/636521/111894840-36322b00-89dc-11eb-8213-36a41fbfa963.png">

![ptam-settings-page](https://user-images.githubusercontent.com/636521/111894849-3df1cf80-89dc-11eb-953f-1c202974114e.png)

![ptam-support-tab](https://user-images.githubusercontent.com/636521/111894857-4e09af00-89dc-11eb-8ae1-0fda0c54ee1a.png)

Please pretty please comment below with your thoughts and any bugs you may find.

**Comment by paaljoachim** [comment]
Hey Ron. Downloaded 5.1.0 version from here: https://github.com/MediaRon/post-type-archive-mapping/releases/tag/5.1.0-beta-1 (Under assets)

Uploaded and installed to a local site.

I noticed this:
<img width="285" alt="Screen Shot 2021-03-22 at 13 34 24" src="https://user-images.githubusercontent.com/5323259/111990258-7647f980-8b13-11eb-90cd-8bbbed572218.png">

It is cute with the heart but the heart creates a distraction, and should be removed.

Going to a page. Clicking the Add Block Inserter. I see this:
<img width="312" alt="Screen Shot 2021-03-22 at 13 37 31" src="https://user-images.githubusercontent.com/5323259/111990699-d048bf00-8b13-11eb-960d-bd4771ab1df1.png">

Again the additional graphic is cute but should not be there. It would be good to remove the colorful icon next to the CUSTOM QUERY BLOCKS title.

Settings -> Custom Query Blocks settings screen.
Clicking to "Disable All Blocks." Hides all the blocks from the Add Block Inserter panel. 

Clicking to "Disable Archive Mapping." Hides any mention of Archive mapping inside the Settings -> Reading Settings screen.

What is...
Clicking to "Disable Page Columns" and "Disable Image Sizes" ?
I am not sure what to look for.

Checking the Custom Query Blocks -> Support tab.
All the links work.

**Comment by ronalfy** [comment]
Thanks @paaljoachim I'll consider removing the heart and the icon. The heart looks funky on your screen, so I'll likely remove.

**Comment by ronalfy** [comment]
Disable Page Columns is when you go to the pages screen in the admin and there's an extra column to show which pages are mapped.

**Comment by ronalfy** [comment]
Image sizes. PTAM creates 4 image sizes. This will prevent them from being created.

**Comment by ronalfy** [comment]
Two of the disable features are based on this review: https://wordpress.org/support/topic/mapping-feature-compromises-the-usefulness-of-the-whole-plugin/

For people that want just the blocks, that is available. For people that want just archive mapping, that is now available as well.

How can I clear up the descriptions?

**Comment by ronalfy** [comment]
@paaljoachim does this make the last options more clear?

<img width="1264" alt="Screen Shot 2021-03-22 at 8 54 07 AM" src="https://user-images.githubusercontent.com/636521/112000710-3cafc800-8aec-11eb-9492-89235ce454e4.png">

**Comment by paaljoachim** [comment]
Ahhh. Thank you for the explanation of what "Disable Page Columns" and "Disable Image Sizes" is.

Rephrasing:

Disable Page Columns
This plugin creates an extra column in the "All Pages" admin screen to show which pages are mapped. Disabling page columns removes the column.

Disable Image Sizes
This plugin creates three image sizes. Which can be seen in the "Featured Image Size" drop down when using the "Custom Posts" block. Disabling image sizes prevents the plugin from creating these each time you upload an image.

**Comment by ronalfy** [comment]
Nice. Thanks.

**Comment by ronalfy** [comment]
Thanks @paaljoachim for the help. This has been released.
